// Author: <your name>
package control;

import entity.Booking;
import entity.Guest;
import entity.MyQueue;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class WalkInRegistrationControl {

    public static final String[] ROOM_TYPES = {"Standard", "Deluxe", "Suite"};
    private static final double[] ROOM_PRICES = {150.00, 250.00, 400.00}; // RM per night

    private MyQueue<Booking> bookingQueue;
    private int bookingCounter;
    private int guestCounter;

    public WalkInRegistrationControl() {
        bookingQueue = new MyQueue<>();
        bookingCounter = 1;
        guestCounter = 1;
    }

    // Returns the price per night for a given room type, or -1 if invalid.
    public double getPriceForRoomType(String roomType) {
        for (int i = 0; i < ROOM_TYPES.length; i++) {
            if (ROOM_TYPES[i].equalsIgnoreCase(roomType)) {
                return ROOM_PRICES[i];
            }
        }
        return -1;
    }

    // Register a new walk-in / standard booking - joins the back of the queue.
    // Guest ID is generated by the system, not typed in by the front-desk user.
    public Booking registerBooking(String name, String contactNumber, String roomType,
                                    int numGuests, LocalDate checkInDate, int nights) {
        Guest guest = new Guest(generateGuestId(), name, contactNumber);
        String bookingId = generateBookingId();
        double price = getPriceForRoomType(roomType);
        Booking booking = new Booking(bookingId, guest, roomType, price, numGuests,
                checkInDate, nights, LocalDateTime.now());
        bookingQueue.enqueue(booking);
        return booking;
    }

    // Returns true only if a booking with this ID currently exists in the queue.
    public boolean bookingExists(String bookingId) {
        for (int i = 0; i < bookingQueue.getSize(); i++) {
            if (bookingQueue.get(i).getBookingId().equalsIgnoreCase(bookingId)) {
                return true;
            }
        }
        return false;
    }

    // Process the next booking in arrival order (assign a room to it)
    public Booking processNextBooking() {
        Booking next = bookingQueue.dequeue();
        if (next != null) {
            next.setStatus("ASSIGNED");
        }
        return next;
    }

    // Cancel a specific booking while it is still waiting in the queue
    public Booking cancelBooking(String bookingId) {
        Booking removed = bookingQueue.removeById(bookingId);
        if (removed != null) {
            removed.setStatus("CANCELLED");
        }
        return removed;
    }

    // View current queue in arrival order (for display / report)
    public Booking[] viewQueue() {
        Booking[] result = new Booking[bookingQueue.getSize()];
        for (int i = 0; i < result.length; i++) {
            result[i] = bookingQueue.get(i);
        }
        return result;
    }

    public int getQueueSize() {
        return bookingQueue.getSize();
    }

    // Total potential revenue of everyone currently waiting in the queue
    public double getTotalQueueRevenue() {
        double total = 0;
        for (Booking b : viewQueue()) {
            total += b.getTotalPrice();
        }
        return total;
    }

    // --- Report 1: bookings sorted by room type, then check-in date ---
    // Manual insertion sort (no Collections.sort / Arrays.sort)
    public Booking[] getBookingsSortedByRoomType() {
        Booking[] bookings = viewQueue();
        for (int i = 1; i < bookings.length; i++) {
            Booking key = bookings[i];
            int j = i - 1;
            while (j >= 0 && compareByRoomTypeThenDate(bookings[j], key) > 0) {
                bookings[j + 1] = bookings[j];
                j--;
            }
            bookings[j + 1] = key;
        }
        return bookings;
    }

    private int compareByRoomTypeThenDate(Booking a, Booking b) {
        int roomCompare = a.getRoomType().compareTo(b.getRoomType());
        if (roomCompare != 0) {
            return roomCompare;
        }
        return a.getCheckInDate().compareTo(b.getCheckInDate());
    }

    // --- Report 2: filter bookings by room type, using linear search ---
    public Booking[] filterByRoomType(String roomType) {
        Booking[] all = viewQueue();
        Booking[] temp = new Booking[all.length];
        int count = 0;
        for (Booking b : all) {
            if (b.getRoomType().equalsIgnoreCase(roomType)) {
                temp[count++] = b;
            }
        }
        Booking[] result = new Booking[count];
        System.arraycopy(temp, 0, result, 0, count);
        return result;
    }

    private String generateBookingId() {
        return String.format("BK%05d", bookingCounter++);
    }

    private String generateGuestId() {
        return String.format("G%04d", guestCounter++);
    }
}
